# Generated by Django 3.0.7 on 2024-05-29 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dengue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_actualizacion', models.TextField(blank=True, db_column='FECHA_ACTUALIZACION', null=True)),
                ('id_registro', models.IntegerField(blank=True, db_column='ID_REGISTRO', null=True)),
                ('sexo', models.IntegerField(blank=True, db_column='SEXO', null=True)),
                ('edad_anos', models.IntegerField(blank=True, db_column='EDAD_ANOS', null=True)),
                ('entidad_res', models.IntegerField(blank=True, db_column='ENTIDAD_RES', null=True)),
                ('municipio_res', models.IntegerField(blank=True, db_column='MUNICIPIO_RES', null=True)),
                ('habla_lengua_indig', models.IntegerField(blank=True, db_column='HABLA_LENGUA_INDIG', null=True)),
                ('indigena', models.IntegerField(blank=True, db_column='INDIGENA', null=True)),
                ('entidad_um_notif', models.IntegerField(blank=True, db_column='ENTIDAD_UM_NOTIF', null=True)),
                ('municipio_um_notif', models.IntegerField(blank=True, db_column='MUNICIPIO_UM_NOTIF', null=True)),
                ('institucion_um_notif', models.IntegerField(blank=True, db_column='INSTITUCION_UM_NOTIF', null=True)),
                ('fecha_sign_sintomas', models.TextField(blank=True, db_column='FECHA_SIGN_SINTOMAS', null=True)),
                ('tipo_paciente', models.IntegerField(blank=True, db_column='TIPO_PACIENTE', null=True)),
                ('hemorragicos', models.IntegerField(blank=True, db_column='HEMORRAGICOS', null=True)),
                ('diabetes', models.IntegerField(blank=True, db_column='DIABETES', null=True)),
                ('hipertension', models.IntegerField(blank=True, db_column='HIPERTENSION', null=True)),
                ('enfermedad_ulc_peptica', models.IntegerField(blank=True, db_column='ENFERMEDAD_ULC_PEPTICA', null=True)),
                ('enfermedad_renal', models.IntegerField(blank=True, db_column='ENFERMEDAD_RENAL', null=True)),
                ('inmunosupr', models.IntegerField(blank=True, db_column='INMUNOSUPR', null=True)),
                ('cirrosis_hepatica', models.IntegerField(blank=True, db_column='CIRROSIS_HEPATICA', null=True)),
                ('embarazo', models.IntegerField(blank=True, db_column='EMBARAZO', null=True)),
                ('defuncion', models.IntegerField(blank=True, db_column='DEFUNCION', null=True)),
                ('dictamen', models.IntegerField(blank=True, db_column='DICTAMEN', null=True)),
                ('toma_muestra', models.IntegerField(blank=True, db_column='TOMA_MUESTRA', null=True)),
                ('resultado_pcr', models.IntegerField(blank=True, db_column='RESULTADO_PCR', null=True)),
                ('estatus_caso', models.IntegerField(blank=True, db_column='ESTATUS_CASO', null=True)),
                ('entidad_asig', models.IntegerField(blank=True, db_column='ENTIDAD_ASIG', null=True)),
                ('municipio_asig', models.IntegerField(blank=True, db_column='MUNICIPIO_ASIG', null=True)),
            ],
            options={
                'db_table': 'dengue_abierto',
                'managed': False,
            },
        ),
        migrations.DeleteModel(
            name='DatosDengue',
        ),
    ]
